### ISSUE TITLE
"Learn more" link in Profiles is leading to the wrong page

### ISSUE THREAD

**Issue by Sergeyp52** [LivePersonInc/knowledge-center-archive#103]
Hi,

When browsing a profile in LEUI and clicking the "Learn more" link in the top left corner, it leads to https://knowledge.liveperson.com/admin-settings-permissions-assign-permissions.html which is an LPA permissions doc and it irrelevant to general profiles.
It should instead lead to https://knowledge.liveperson.com/admin-settings-permissions-customize-permissions.html which is the actual doc containing a list of all role/profile configurations.

In addition, it's impossible to find this link by searching for the word "Profiles" which I believe should be one of the major index words for this page.

Thanks,
Sergey

**Comment by EdenKupe** [comment]
Hey,

I changed the redirect. As for "profiles" hitting this page in search, I agree. @DavLipman can we look at renaming this document? It's called "customize permissions" but everything it talks about is profiles + users see this section as profiles in the UI.

Thanks!

**Comment by DavLipman** [comment]
FYI the document has been renamed to Profiles.
Thanks
Davina

Davina Lipman
Product Writer
T: +972-74-700-4557
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/liveperson/?ref=bookmarks>
Our mission is to make life easier by transforming how people communicate
with brands. <https://liveperson.docsend.com/view/drieh2u>


On Sun, Sep 1, 2019 at 10:48 AM Eden Kupermintz <notifications@github.com>
wrote:

> Hey,
>
> I changed the redirect. As for "profiles" hitting this page in search, I
> agree. @DavLipman
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DavLipman&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=izqnYDVpkQMyqGBGIlUtRuTZ3Iu3Zh2k294a3eW6SIo&s=yUhsggPkzAS3Yv2Md6tinrRSVKdtK12Yo_Nl_5u_FlY&e=>
> can we look at renaming this document? It's called "customize permissions"
> but everything it talks about is profiles + users see this section as
> profiles in the UI.
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_103-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJNQH7PBNXVN7Q7O42XC2J3QHNXWDA5CNFSM4ISL6DPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5T4W7Y-23issuecomment-2D526895999&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=izqnYDVpkQMyqGBGIlUtRuTZ3Iu3Zh2k294a3eW6SIo&s=pKupHbHp5uKQnm02WYSe13Q1Nv-RX3JnH8HhTL34HXY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNQH7P3KWAGAZSLS35L7STQHNXWDANCNFSM4ISL6DPA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=izqnYDVpkQMyqGBGIlUtRuTZ3Iu3Zh2k294a3eW6SIo&s=7zXIhAecOmt8HEpY6mHF5eamHMzAQUk2uxjVnvW5cDQ&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
Nice!
