### ISSUE TITLE
Embedded HTML engagement accessibility - no keyboard support

### ISSUE THREAD

**Issue by joannem81** [LivePersonInc/knowledge-center-archive#104]
When creating an embedded engagement the button to open the chat window does not work with a keyboard. I should be able to use the tab key to focus on the button and then use either the enter or space keys to press the button. Currently the button can only be pressed with a mouse or using a touch enabled device.
The code that is injected by LivePerson is using a div with role=button and tabindex="0" so I can tab to focus on the button however keyboard events will need to be added manually using JavaScript. Preferably use a button or link instead so that keyboard events are built in. Example code I see injected into my container:
```
<div id="LPMcontainer-1567175284117-0" class="LPMcontainer LPMoverlay" role="button" tabindex="0" style="margin: 1px; padding: 0px; border-style: solid; border-width: 0px; font-style: normal; font-weight: normal; font-variant: normal; list-style: none outside none; letter-spacing: normal; line-height: normal; text-decoration: none; vertical-align: baseline; white-space: normal; word-spacing: normal; background-repeat: repeat-x; background-position: left bottom; cursor: auto; display: block; position: relative; top: 0px; left: 0px;">
    <!-- My custom HTML inserted here -->
</div>
```
I also noticed this same problem on many buttons on the liveperson.com site which means the website is completely inaccessible to many users of assistive technologies including screen readers.

**Comment by EdenKupe** [comment]
Hey @joannem81 !

Thanks for opening this issue. This is one of our documentation sites but I'll forward both your requests to the relevant teams within the company.

Thanks again!
