### ISSUE TITLE
No Chat Option Available

### ISSUE THREAD

**Issue by uaikal** [LivePersonInc/knowledge-center-archive#110]
Hi,

I've followed the instructions mentioned in this link https://knowledge.liveperson.com/getting-started-add-the-liveperson-tag-to-your-website.html

But chat option/button is not coming. Attaching my sample html file.

[liveperson.zip](https://github.com/EdenKupe/knowledge-center/files/3626589/liveperson.zip)

**Comment by EdenKupe** [comment]
Hey!

Thanks for opening an issue but this space is for our Knowledge Center, not general support. To get support, please navigate to [www.liveperson.com](www.liveperson.com) and click to chat with our support team. You can also click to chat from the Knowledge Center itself, there's a chat button at the bottom right hand side of the site.

Thanks!
