### ISSUE TITLE
Incomplete explanation on page: Add the LivePerson tag to your website

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#12]
On this article
https://knowledge.liveperson.com/getting-started-add-the-liveperson-tag-to-your-website.html

There's a line that says
"If the tag is included a javascript file, be sure to omit the"

but the sentence is not completed.

I'm assuming the explanation of what exactly needs to be omitted from the monitor tag retrieved from LEUI needs to be added here.

**Comment by EdenKupe** [comment]
@lidat can you take a look please?

**Comment by lidat** [comment]
resolved! thanks @ykorogi
