### ISSUE TITLE
Channel Capability table doesn't scroll horizontally when browser is extra wide

### ISSUE THREAD

**Issue by trosel** [LivePersonInc/knowledge-center-archive#129]
https://knowledge.liveperson.com/messaging-channels-messaging-channels-capabilities-comparison.html

I believe it's related to the css of the table in this file https://github.com/EdenKupe/knowledge-center/blob/master/pages/documents/Messaging%20Channels/messaging%20capabilities%20comparison.md

**Comment by EdenKupe** [comment]
This is not something which happens automatically, I'll have to develop it.
