### ISSUE TITLE
MCS now supports Italian and Japanese

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#13]
I noticed that in this internal release note, MCS now supports Italian and Japanese.
https://docs.google.com/document/d/1PyDWFRfLEqRDbG64qp04xw1u4Sn5v4_X6ObRgHgjl7s/edit

Would you also update this information on this page?

https://knowledge.liveperson.com/data-reporting-meaningful-connection-score-(mcs)-meaningful-connection-score-(mcs)-overview.html

*I received a support chat from Japanese client asking why MCS started reflecting from April 1, 2019. And I noticed only after going through above internal release note that MCS now supports Japanese.

**Comment by EdenKupe** [comment]
@DavLipman please review and correct as needed :)

**Comment by DavLipman** [comment]
Thanks for your comment. I have updated this document to reflect this comment.

**Comment by ykorogi** [comment]
@DavLipman 

@DavLipman 

In the internal release note of MCS, it also says
"Custom lexicon per account is not supported in Japanese language. Japanese lexicon can only be updated via code change & rollout of the service."

However, on Kknowldge Center it says "The MCS model can be customized per account,"

This may cause a bit of misunderstanding, for Japanee accounts. Therefore, I suggest above limitation regarding Japanese should also be added.

**Comment by DavLipman** [comment]
Thanks for your feedback - the article has been updated.
