### ISSUE TITLE
https://knowledge.liveperson.com/ai-bots-automation-post-conversation-survey-bot.html#prerequisites

### ISSUE THREAD

**Issue by KevinMcgachySky** [LivePersonInc/knowledge-center-archive#14]
Available channels needs updated. 

For web messaging:
Structured content needs to be enabled by your LivePerson Account Manager. No further configuration is needed on the client side.

A brand that is looking to add the Survey Bot to its ranks should consider the following:

The Survey Bot is available for Web messaging and In-app messaging only.
SMS, Facebook, LINE and other sources will be supported starting **9.30.18.**

**Comment by DavLipman** [comment]
Thanks for your message. I have updated the article as per your comment.
