### ISSUE TITLE
Add vanity URL to the firewall config instructions document

### ISSUE THREAD

**Issue by igor-liveperson** [LivePersonInc/knowledge-center-archive#142]
https://knowledge.liveperson.com/security-regulations-security-configuring-your-firewall.html

It needs to clearly call out that any vanity URL domains also must be listed as it will prevent the functionality of LiveEngage for end users.

**Comment by EdenKupe** [comment]
@DavLipman can you take a look please?

**Comment by DavLipman** [comment]
Thank you for your comment. 
A section on vanity URL has been added to this document.
