### ISSUE TITLE
Incorrect Link for Metric Glossary

### ISSUE THREAD

**Issue by mwashburn91** [LivePersonInc/knowledge-center-archive#150]
https://knowledge.liveperson.com/data-reporting-report-builder-report-builder-user-guide-(standard).html#metrics-glossary

Last section in here has a click here that points to a dead link in the developer's portal.  The correct link is the following: https://knowledge.liveperson.com/data-reporting-reporting-metrics.html

**Comment by cshort-lp** [comment]
Thanks @mwashburn91 I'll take care of it right now.

**Comment by cshort-lp** [comment]
https://github.com/EdenKupe/knowledge-center/commit/40819b1e3a1bb0a591cc6ff49dce1cf610c07220
