### ISSUE TITLE
Idle conversation status information is incorrect

### ISSUE THREAD

**Issue by jeremywest1970** [LivePersonInc/knowledge-center-archive#152]
The article states "Idle conversation status and filter: When a consumer hasn't responded in five minutes or longer, a conversation is marked with the new idle status. You can filter these conversations out for a more focused conversation list."

this is not a standard 5 minutes.  It is based on the Time to Inactive setting in Smart capacity.  this was tested and confirmed.

Please correct

**Comment by EdenKupe** [comment]
Which article is this?

**Comment by cdougherty328** [comment]
Thanks for your feedback Jeremy. I've now updated the Enhanced agent workspace user guide to reflect this change.
