### ISSUE TITLE
URL Slug is case-sensitive

### ISSUE THREAD

**Issue by andrewstefanik** [LivePersonInc/knowledge-center-archive#16]
URL Slug is case sensitive, for example:

https://knowledge.liveperson.com/troubleshooting-har-files-and-web-requests.html returns a 404, but https://knowledge.liveperson.com/Troubleshooting-har-files-and-web-requests.html takes you to the desired page.

This could be expected behavior, but I figured I'd bring it to your attention.

Thanks!

**Comment by EdenKupe** [comment]
Hey,

Thanks for reporting. The URL simply shouldn't have that capital "T" is that's not conventional. I'll fix it :)

**Comment by EdenKupe** [comment]
Done!
