### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by yilevitzky** [LivePersonInc/knowledge-center-archive#17]
Hello,
Yoel Ilevitzky from Tier 2\HD IL.
We had consumers in chat saying that they can't find the option to activate Advanced Workload Distribution, although they do have 2 agent groups.
They were missing features, and the problem is that the document doesn't specify that in order to use it, features need to be activated through the Account Team (as specified in other articles).
Please add this, to notify consumers, so they can contact their account team directly.

Doc link:
https://knowledge.liveperson.com/contact-center-management-live-chat-operations-agent-groups-workload-distribution.html

Internal doc link, specifying which features need to be activated: (frame no.4)
https://docs.google.com/presentation/d/1VGB8IKhulCwRzFPbrxB0XMs2NIi5LHrujtwvLLq1VTM/edit#slide=id.g156cb2c450_0_0

Thanks

**Comment by lonz87** [comment]
@yilevitzky I have added "Advanced workload distribution need to be activated through your LivePerson Account Team." as a note to the 'Advanced workload distribution' section. Thanks for you feedback let me know if this suffices.
