### ISSUE TITLE
Screenshot needs changing

### ISSUE THREAD

**Issue by wrijpkema** [LivePersonInc/knowledge-center-archive#178]
Within the article 'Performance dashboard for messaging', the screenshot shown with the 'Brand level data sheet - main panel' (https://knowledge.liveperson.com/data-reporting-messaging-messaging-dashboards-performance-dashboard-for-messaging.html#brand-level-data-sheet---main-panel) is that of the 'Main panel: agent performance summary' (same as above in the article). Could you please change this with a screenshot 'Brand level data sheet - main panel'? TIA!

**Comment by EdenKupe** [comment]
@DavLipman can you please take care of this?

**Comment by DavLipman** [comment]
sure - i'm on it.

Davina Lipman
Product Communications
T: +972-74-700-4557
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Making life easier for people and brands everywhere through trusted
conversational AI
<https://www.liveperson.com/resources/news/liveperson-named-one-of-fast-companys-most-innovative-companies/?utm_medium=email&utm_source=gmail&utm_campaign=signature&utm_content=fastco>


On Sun, Apr 12, 2020 at 12:24 PM Eden Kupermintz <notifications@github.com>
wrote:

> @DavLipman
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DavLipman&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=TxhE5OWAnSANJXuiwQzj1joiGGi9Dkgcn_N0wrILUhM&s=PcTeUBX5B6JquqZwj4Capls4OMPawZVkbhytq5tDDNk&e=>
> can you please take care of this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_178-23issuecomment-2D612587340&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=TxhE5OWAnSANJXuiwQzj1joiGGi9Dkgcn_N0wrILUhM&s=Oiu0Z5Jzh77D2A0KrlwVw3zV5LEvylSuxizTJJoTVSc&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNQH7LOVBNFVXRXPU4II4LRMGCGHANCNFSM4MFHNIUA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=TxhE5OWAnSANJXuiwQzj1joiGGi9Dkgcn_N0wrILUhM&s=hclLM6nBbUPJlfzudTRLq7QilLkJdX6CqiDTcomc314&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by DavLipman** [comment]
I updated the screen shot. Thanks for the feedback
