### ISSUE TITLE
Info about MCS available languages needs update (not consistent)

### ISSUE THREAD

**Issue by EdnaLP** [LivePersonInc/knowledge-center-archive#182]
Info on this site needs update

about MCS available languages:
"MCS is available in: English, Spanish, Italian and Japanese."
https://knowledge.liveperson.com/admin-settings-supported-languages.html#languages-supported-by-mcs

more up to date info:
"The MCS is available in English, French, Italian, Japanese, German and soon in Spanish too."
https://knowledge.liveperson.com/data-reporting-meaningful-connection-score-(mcs)-meaningful-connection-score-(mcs)-overview.html

**Comment by EdenKupe** [comment]
@DavLipman is this yours?

**Comment by DavLipman** [comment]
Yes- I’ll fix it

On Wed, 22 Apr 2020 at 15:45 Eden Kupermintz <notifications@github.com>
wrote:

> @DavLipman
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DavLipman&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=wfx7gw5QPKbq3zLClQ_poeuDf3droECueyv4B7ASO3I&s=pWFG-u_WlBkIfkpnUFDRZSwYrejFsOim-Hv0I8z5O_I&e=>
> is this yours?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_182-23issuecomment-2D617756995&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=wfx7gw5QPKbq3zLClQ_poeuDf3droECueyv4B7ASO3I&s=uZcoIsOXtu65xbDGk17k9S_i40cG7gxqqek-hjEgMtE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNQH7NBOEAIBGQ7DCUZAGLRN3RG5ANCNFSM4MOEIAYA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=wfx7gw5QPKbq3zLClQ_poeuDf3droECueyv4B7ASO3I&s=i7cLwyizdbw_GWt_VfJ_vqVbzKeDUvfiv1bcSMTF52A&e=>
> .
>
-- 

Davina Lipman
Product Communications
T: +972-74-700-4557
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Making life easier for people and brands everywhere through trusted
conversational AI
<https://www.liveperson.com/resources/news/liveperson-named-one-of-fast-companys-most-innovative-companies/?utm_medium=email&utm_source=gmail&utm_campaign=signature&utm_content=fastco>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by DavLipman** [comment]
I have updated the languages of MCS and fixed the inconsistency.
Many thanks for the feedback.
