### ISSUE TITLE
Link for case management support page doesn't work.

### ISSUE THREAD

**Issue by psollom** [LivePersonInc/knowledge-center-archive#19]
When I search for case management, i click link to one of the results and it takes me to this page which responds with a 404 error.
https://knowledge.liveperson.com/Troubleshooting-case-management-support.html

**Comment by EdenKupe** [comment]
Notice the capital T in your URL. If you change it to lower case, the link will work. This was an issue on our end that created the wrong link but is now fixed.

**Comment by psollom** [comment]
Thanks. It works with the lower case t. However, the search still takes me
to the link with the capital.

On Sun, 14 Apr 2019 at 17:32, Eden Kupermintz <notifications@github.com>
wrote:

> Closed #19
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_19&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=oq0uE2W--k72zypJ_seFiVmedscHTbctC8ZHnkxbmUU&s=bEBu8uuC6zYOxD1f3SFZjjdkSFeoszpanVLvvtbmE60&e=>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_19-23event-2D2274936552&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=oq0uE2W--k72zypJ_seFiVmedscHTbctC8ZHnkxbmUU&s=DJtM5_J7XrfUFoXj3glxjqhsnLH4EG3XickO30rkva0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AuzURQO-2DzAcC8gZjtEvp7byzA7vaTEXqks5vg1gDgaJpZM4cr4Rn&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=oq0uE2W--k72zypJ_seFiVmedscHTbctC8ZHnkxbmUU&s=iyzIsYDW0k0QPjD_yn449RhDVKyX1OfWk1SOWgmHHaY&e=>
> .
>


-- 

Patrick Sollom
Premium Support Engineer
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.
<https://bit.ly/2RS120I>
LivePerson UK Ltd., Registered No. 4045110 in England and Wales;
16 Great Queen Street, London WC2B 5DG

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
Odd. I'll look into it.

**Comment by psollom** [comment]
Thanks.
I should mention I ran in incognito mode to rule out a cache issue.

On Mon, 15 Apr 2019 at 14:36, Eden Kupermintz <notifications@github.com>
wrote:

> Odd. I'll look into it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_19-23issuecomment-2D483254465&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=S4rLTrxyWjS-uqM5HKUBLh9MZBiihw54OEl9_I0xuZg&s=et32cbWtelI3qJZyMNMnB-w5g1iic7PO5086cdj47HU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AuzURWD5rM5FfxGRBVS-5FDObGMGSHiIZzks5vhIBugaJpZM4cr4Rn&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=S4rLTrxyWjS-uqM5HKUBLh9MZBiihw54OEl9_I0xuZg&s=hYvi4ey9E3Sn6TojgQHKaA0TzSNQeDWiA3IAmWrhL0E&e=>
> .
>


-- 

Patrick Sollom
Premium Support Engineer
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.
<https://bit.ly/2RS120I>
LivePerson UK Ltd., Registered No. 4045110 in England and Wales;
16 Great Queen Street, London WC2B 5DG

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
Seems to be fixed now :)

**Comment by psollom** [comment]
Im not finding it in the results now.
https://support.liveperson.com/?s=case+management

On Mon, 15 Apr 2019 at 16:16, Eden Kupermintz <notifications@github.com>
wrote:

> Seems to be fixed now :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_19-23issuecomment-2D483295005&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=DOBDoNaAIVCtu_K0Ufugc-eiFVlRH6-_-VwdTMPQpsI&s=zB1Si6VDtOIPoxkEWL1dRNgab_foKUhd1KMyZHuc-88&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AuzURcydromDmIOrp-5Fxmc-2DjM5L7uO7JEks5vhJfGgaJpZM4cr4Rn&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=DOBDoNaAIVCtu_K0Ufugc-eiFVlRH6-_-VwdTMPQpsI&s=Kxncil0dkcd4eZz-tI5akzdgKBxlmucPmGYHr0RVLiI&e=>
> .
>


-- 

Patrick Sollom
Premium Support Engineer
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.
<https://bit.ly/2RS120I>
LivePerson UK Ltd., Registered No. 4045110 in England and Wales;
16 Great Queen Street, London WC2B 5DG

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
That's the support.liveperson.com search, I sadly don't maintain that part. I fixed the issue in the knowledge.liveperson.com search.

**Comment by psollom** [comment]
oh sorry! wrong page. Yes, all good now.

On Mon, 15 Apr 2019 at 16:23, Eden Kupermintz <notifications@github.com>
wrote:

> That's the support.liveperson.com search, I sadly don't maintain that
> part. I fixed the issue in the knowledge.liveperson.com search.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_19-23issuecomment-2D483297930&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=oc9Jl1z6xHzzs3nzAJJ6DescPvbKpFLBzN1xL6iBBvk&s=FuC-UF53sUvKkRsIMFCWeqp4OFK1XN10GrcOoCs83LU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AuzURVobTBEbB9vgRvPbKO95AABm9mAjks5vhJl6gaJpZM4cr4Rn&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=H2IYGufGY227pkU8X9RZGPFhzeznDVlu9YnwcVF0IXA&m=oc9Jl1z6xHzzs3nzAJJ6DescPvbKpFLBzN1xL6iBBvk&s=Bdm2ZuxQ7M-23loNmWaCbsZgcZMGw2QB2lrNLntEllA&e=>
> .
>


-- 

Patrick Sollom
Premium Support Engineer
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.
<https://bit.ly/2RS120I>
LivePerson UK Ltd., Registered No. 4045110 in England and Wales;
16 Great Queen Street, London WC2B 5DG

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
