### ISSUE TITLE
Salesforce integration document is not the updated one

### ISSUE THREAD

**Issue by oferzeh** [LivePersonInc/knowledge-center-archive#2]
Hi

The document is not aligned with the one of the connection panel:
https://s3-eu-west-1.amazonaws.com/ce-sr/CA/Factsheets/SFDC+Widget+for+LiveEngage+-+Installation+and+Configuration+Guide.pdf

Cheers,
Ofer

**Comment by EdenKupe** [comment]
This was fixed by @cdougherty328 following an email :)
