### ISSUE TITLE
MCS toolkit section of knowledge center needs updating

### ISSUE THREAD

**Issue by tblevins** [LivePersonInc/knowledge-center-archive#207]
MCS toolkit needs updating as it is now part of the platform and no longer requires a separate login along with the updates on how it looks different between livechat and messaging conversations.  New screenshots need to be taken there to match with the new agent workspace and where MCS toolkit can be launched. -- Please review.

**Comment by DavLipman** [comment]
Thanks for the comment. I will work with the PM to update the article. Just FYI the MCS toolkit will be deprecated by the end of the year.
