### ISSUE TITLE
Clicking on image arrow doesnt work

### ISSUE THREAD

**Issue by lonz87** [LivePersonInc/knowledge-center-archive#23]
Video does not seem to be embedded. Need to also embed April newsletter release today.

**Comment by lonz87** [comment]
Also @EdenKupe from the newsletter email for example, when you click on the link to release notes/ another KC article, the left navigation doesn't open to show them where they are... can you fix that? @lidat FYI

**Comment by EdenKupe** [comment]
Hey,

Which video are you referring to? Newsletter video has been embedded.

As for your second question (which should really be another issue) I don't really understand the bug. Let's sync face to face.

**Comment by lonz87** [comment]
OK thanks! When people click on the video/release notes from the email which leads to whats new article, the left navigation does not open to show them where they are located.
