### ISSUE TITLE
Getting a 404 for the Knowledge Base / Maven details page

### ISSUE THREAD

**Issue by sshorr** [LivePersonInc/knowledge-center-archive#27]
Getting a 404 for the Knowledge Base / Maven details page

https://knowledge.liveperson.com/bots-automation-conversation-builder-components-knowledge-base.html

**Comment by EdenKupe** [comment]
Hey,

Can I ask where you got this link? I don't see such a page in the knowledge center.

**Comment by sshorr** [comment]
Hey @EdenKupe , tried to do a search for Knowledge Base (just type "kn" and it'll try to preview something, but the link is dead.

**Comment by EdenKupe** [comment]
The document has been removed from the search and this link now redirects to the conversation builder overview.
