### ISSUE TITLE
IP restriction page link has the wrong URL.

### ISSUE THREAD

**Issue by LPnsteenstra** [LivePersonInc/knowledge-center-archive#28]
the IP address blocking link on knowledge.liveperson.com is broken.  Currently, it links to:
https://knowledge.liveperson.com/security-regulations-security-IP-address-blocking.html
which returns a 404.  
 The correct address is:
https://knowledge.liveperson.com/security-regulations-security-ip-address-blocking.html 

The difference is the capitalized IP in the incorrect address.

Thanks for your time!

**Comment by EdenKupe** [comment]
Fixed, thank you!
