### ISSUE TITLE
Missing SSO link for legacy platform

### ISSUE THREAD

**Issue by lp-tattwell** [LivePersonInc/knowledge-center-archive#29]
On this page: https://knowledge.liveperson.com/security-regulations-sso-unified-login.html

There are SSO 4 links but there is a 5th for logging in to the legacy platform.

https://{{domain}}/hc/s-{{accountId}}/web/m-LP/samlAssertionMembersArea/home.jsp?redirectToLiveEngage=false&ac=true

Also, all the 4 URLs just have a spaces instead of a {{domain}} placeholder.

**Comment by EdenKupe** [comment]
Hey,

The issue with the domain placeholder has been resolved. However, I'm not sure that we want to expose that legacy link. @lonz87 can you look into this?

**Comment by lonz87** [comment]
Not sure what to do here, it's @DavLipman article, but I can easily remove the 5th URL until clarified.

**Comment by EdenKupe** [comment]
@lp-tattwell is the issue that the link was missing? Because it's in there now :)

**Comment by lp-tattwell** [comment]
Yep, the link being missing is the only thing. I can't see it though in the list of URLs.

I can't count; there are 5 there and this will be the 6th.

**Comment by EdenKupe** [comment]
Got it, should be fixed on Sunday.

**Comment by lonz87** [comment]
@EdenKupe did you handle this or is there something from my end? @DavLipman did you get a chance to see this thread?

**Comment by EdenKupe** [comment]
Need confirmation that this link is:

1) Legacy

2) That if it's legacy, we need to remove it

**Comment by lonz87** [comment]
link removed, @EdenKupe can close please
