### ISSUE TITLE
cobrowse needs updating

### ISSUE THREAD

**Issue by tblevins** [LivePersonInc/knowledge-center-archive#31]
cobrowse settings need to be updated to also reflect web messaging and not just say it's "LiveChat" as these configurations in night vision affect either LiveChat or Web Messaging.

**Comment by EdenKupe** [comment]
@lonz87 can we get this fixed please?

**Comment by lonz87** [comment]
hey @tblevins are you looking at: https://knowledge.liveperson.com/agent-manager-workspace-agent-tools-for-messaging-cobrowse-for-messaging.html ? 

We have one for CoBrowse live chat and one for CoBrowse messaging. Please let me know if knowing those 2 separate articles answers your Q, and if not, then which you are referring to. Thanks!

**Comment by EdenKupe** [comment]
@tblevins have you seen Elana's question above?

**Comment by EdenKupe** [comment]
Hey,

Going to close this issue for now. If you end up coming back, feel free to re-open it :)
