### ISSUE TITLE
"How to export 100,000 chats into a dashboard" article gives 404 error

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#33]
Article **"How to export 100,000 chats into a dashboard**" is missing in Knowledge center, although it comes up in search result and also link exists under Data & reporting >  Live Chat 

For example: If you come across above article and click the link in search result, you get 404 error .
The URL that is giving 404 error is 
https://knowledge.liveperson.com/data-reporting-live-chat-how-to-export-100000-chats-into-a-dashboard.html

I remembered this article existed in Connection Area so looked for it in Knowledge Center today and noticed that there's something wrong with this article.

Would you please make sure this article is available?

Thank you!

Regards,
Yuri Korogi

**Comment by EdenKupe** [comment]
Fixed :)
