### ISSUE TITLE
Secure forms for messaging user guide

### ISSUE THREAD

**Issue by Shachar88** [LivePersonInc/knowledge-center-archive#35]
https://knowledge.liveperson.com/security-regulations-secure-forms-secure-forms-for-messaging-user-guide.html   

Video and text say only for in-app messaging now, in future for web.
However it is available for web messaging,

**Comment by EdenKupe** [comment]
@lonz87 can you please review?

**Comment by lonz87** [comment]
I need to check with davina because i think the entire **user guide needs to be rewritten to include web messaging** now, as it is written with just in-app in mind. Also, video needs to be edited by Eitan. I am writing them an email and will follow up Sunday to explain. @DavLipman

**Comment by lonz87** [comment]
being handled

**Comment by lonz87** [comment]
@DavLipman can you update status?

**Comment by DavLipman** [comment]
Video to be edited. Article talks about secure forms in general (with a section on Mobile App)

**Comment by DavLipman** [comment]
Issue closed

Davina Lipman
Product Writer
T: +972-74-700-4557
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>


On Mon, Jun 3, 2019 at 1:11 PM lonz87 <notifications@github.com> wrote:

> @DavLipman
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DavLipman&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=-5PkSlLmWpbkHvLDkwZTZYXCM-fDmOirCFIl-3dpQlU&s=CD77YGU8mqryLs6LO3yu5xrag-d68WoeENNzDEWQbzI&e=>
> can you update status?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_35-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJNQH7PTBP46NKVE5VBM4NLPYTU5DA5CNFSM4HO7NWK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWY6FYY-23issuecomment-2D498197219&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=-5PkSlLmWpbkHvLDkwZTZYXCM-fDmOirCFIl-3dpQlU&s=rsXloANwTa8Z5uh66voly2Japn5LOEJk0sFebaiKyVo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNQH7MNPKWHJLSYWSU3ZB3PYTU5DANCNFSM4HO7NWKQ&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=-5PkSlLmWpbkHvLDkwZTZYXCM-fDmOirCFIl-3dpQlU&s=CvogDu0MaE4gPcpKIhSyaXV_r9U3yw-RObpMF9br6RM&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by DavLipman** [comment]
Waiting for video to be updated in order to close issue.

**Comment by EdenKupe** [comment]
@DavLipman can we close this?

**Comment by DavLipman** [comment]
The video has now been updated.
