### ISSUE TITLE
Grammar in "Getting started with Conversational Commerce"

### ISSUE THREAD

**Issue by globalcrowd** [LivePersonInc/knowledge-center-archive#4]
Is it "Maven's" or "the Maven"?

... the Maven's Recommended Actions capability looks at each conversational turn and recommends to the agent the next action for the best possible conversational outcome.

**Comment by EdenKupe** [comment]
Hey,

Thanks for reporting! @lonz87 can you take a look?

**Comment by lonz87** [comment]
I took out the word "the", thanks for the feedback! @globalcrowd
