### ISSUE TITLE
Punctuation error in the Entry point document

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#40]
The note below https://knowledge.liveperson.com/contact-center-management-campaigns-entry-point.html#assigning-an-entry-point-to-your-engagement

"Note: Entry points are shared throughout your account, so if yfou modify an entry point, the change will be applied to any other engagements that use this entry point."

"yfou" is obviously not correct.

**Comment by cdougherty328** [comment]
This typo has been fixed

**Comment by cdougherty328** [comment]
This has been resolved

On Mon, May 27, 2019 at 10:38 AM Hmalchev <notifications@github.com> wrote:

> The note below
> https://knowledge.liveperson.com/contact-center-management-campaigns-entry-point.html#assigning-an-entry-point-to-your-engagement
>
> "Note: Entry points are shared throughout your account, so if yfou modify
> an entry point, the change will be applied to any other engagements that
> use this entry point."
>
> "yfou" is obviously not correct.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_40-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJNPHYGPNXKYL7U436ZFI3TPXOFV7A5CNFSM4HPZLRS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GV6YYPQ&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cpq5JVh26K4-Ed4vzMzCnDMSeQefx91O6_-lfjrscMw&m=f38bm9UOJ8NkG2NW8yPsqxThZYBNPKK2RsQNvv__-Qk&s=_dNtTEJuph6WryYN-vMjzX0yze2gdsQdoPHo9S5w9rg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNPHYB755AOJ52UZ2GUBGLPXOFV7ANCNFSM4HPZLRSQ&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cpq5JVh26K4-Ed4vzMzCnDMSeQefx91O6_-lfjrscMw&m=f38bm9UOJ8NkG2NW8yPsqxThZYBNPKK2RsQNvv__-Qk&s=bybxKHvWHdHGJzEhCx0aFgXZrrYXuojbx8tc6h8miVU&e=>
> .
>


-- 

Chloe Dougherty
Product Writer
T: +972-74-700-4836
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
