### ISSUE TITLE
Grammar error in the managing campagns document

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#41]
https://knowledge.liveperson.com/contact-center-management-campaigns-managing-campaigns.html#engagement-not-displaying-as-expected
this document has an mistake
"Your Campaign Targeting Settings:
    Make sure that you are belong to the campaign’s target audience?"
to be correct, it needs to be: "Make sure that you belong to the campaign’s target audience?"

**Comment by cdougherty328** [comment]
This has been fixed

**Comment by cdougherty328** [comment]
This has been resolved

On Mon, May 27, 2019 at 11:44 AM Hmalchev <notifications@github.com> wrote:

>
> https://knowledge.liveperson.com/contact-center-management-campaigns-managing-campaigns.html#engagement-not-displaying-as-expected
> this document has an mistake
> "Your Campaign Targeting Settings:
> Make sure that you are belong to the campaign’s target audience?"
> to be correct, it needs to be: "Make sure that you belong to the
> campaign’s target audience?"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_41-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJNPHYBFLQELLY65YDVGQF3PXONN5A5CNFSM4HPZ22X2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GV7FWPA&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cpq5JVh26K4-Ed4vzMzCnDMSeQefx91O6_-lfjrscMw&m=ThReMXTUR7d3yaCY1iamWLKISv6I4U3bljwRGO-KtUI&s=bq0yyw4yTrcZy8XrO68WYn0cjsI91TYreYdQaPujghE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNPHYFLMYYTALCQY7SQRSLPXONN5ANCNFSM4HPZ22XQ&d=DwMFaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=cpq5JVh26K4-Ed4vzMzCnDMSeQefx91O6_-lfjrscMw&m=ThReMXTUR7d3yaCY1iamWLKISv6I4U3bljwRGO-KtUI&s=CiRpTHd-H7roKwxIU1Hs1YGTuz28CC9seqFymtOQx5Y&e=>
> .
>


-- 

Chloe Dougherty
Product Writer
T: +972-74-700-4836
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
