### ISSUE TITLE
Advanced window configuration and customization black screenshot

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#42]
https://knowledge.liveperson.com/contact-center-management-campaigns-engagement-window.html#advanced-window-configuration-and-customization 
Black screenshot.

**Comment by cdougherty328** [comment]
I don't see a black screenshot here, all images seem to be displaying properly. Which one are you referring to?

**Comment by Hmalchev** [comment]
first one wasn't loading the gif, it loaded correctly on repeat loads.
Case closed.

**Comment by Hmalchev** [comment]
Issue turns out to be with the gif, unlike all others, doesn't loop after the first animation, so after finishing, it shows only a black window.
