### ISSUE TITLE
Secure forms for messaging has a typo

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#44]
https://knowledge.liveperson.com/security-regulations-secure-forms-secure-forms-for-messaging-user-guide.html#experience
in this part of the document, under push notifications:
"If the your app is running in the background"
this needs to be either:
"If your app is running in the background" or
"If the app is running in the background"

**Comment by DavLipman** [comment]
Thank you for the feedback. The article has been updated.
