### ISSUE TITLE
Authenticated web messaging correction

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#49]
https://knowledge.liveperson.com/messaging-channels-web-messaging-authenticated-web-messaging.html
has an error here
"Authenticated web messaging can be offered to consumers are authenticated on your website,"
needs to be 
"Authenticated web messaging that can be offered to consumers are authenticated on your website,"

**Comment by cdougherty328** [comment]
This has been resolved
