### ISSUE TITLE
Multiple highlighted menu items when following internal links

### ISSUE THREAD

**Issue by globalcrowd** [LivePersonInc/knowledge-center-archive#5]
When following a link in the knowledge center, both the previous menu item and the new menu item are highlighted in blue. When clicking on yet another link, **all three items** are highlighted in the menu.

Not sure if this may be intentional?

Tested in Firefox and Chrome

**Comment by EdenKupe** [comment]
Hey,

Thanks for reporting. I'm aware and will fix :)

**Comment by EdenKupe** [comment]
Hey,

This is fixed. There's another issue with the sidebar not collapsing properly which I'll fix as well :)
