### ISSUE TITLE
missing pic and reference to account team to open feature

### ISSUE THREAD

**Issue by shmulikgazit** [LivePersonInc/knowledge-center-archive#51]
Hi Eden,

Here: https://knowledge.liveperson.com/messaging-channels-live-chat-displaying-chat-engagements.html#2-button-refresh

I believe we should add
1. screenshot of where to find the refresh engagement checkmark
2. Reference that this is not a default feature and if needed, to contact the account team

Thanks!

**Comment by cdougherty328** [comment]
These additions have now been made to the document, thanks!
