### ISSUE TITLE
Link doesn't work.

### ISSUE THREAD

**Issue by Shachar88** [LivePersonInc/knowledge-center-archive#52]
This link doesn't work https://knowledge.liveperson.com/admin-settings-skills-groups-operate-business-divisions-from-one-account.html

**Comment by lonz87** [comment]
@EdenKupe @cdougherty328 whats status?

**Comment by EdenKupe** [comment]
@Shachar88 I believe this is solved, can you try searching for the term again and seeing if the link works?

**Comment by Shachar88** [comment]
Seems to be fine now.

On Mon, Jun 3, 2019 at 7:47 PM Eden Kupermintz <notifications@github.com>
wrote:

> @Shachar88
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Shachar88&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=AAyMc3HyvNY4xrJwcNGRFDnCT97iBHn6GqTfzmbL-gM&m=GvkpohlKeNF4NEWd5qv2ilCAdl6qp26j3AobueHbvsw&s=cJwI6OGHILpQH3TZVVcfVbPY4eoC1YzUagEwUjuEvRA&e=>
> I believe this is solved, can you try searching for the term again and
> seeing if the link works?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_52-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAH5VLU22AWJ5O23UN4OVCQDPYVDKTA5CNFSM4HQMGAYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW2AEOY-23issuecomment-2D498336315&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=AAyMc3HyvNY4xrJwcNGRFDnCT97iBHn6GqTfzmbL-gM&m=GvkpohlKeNF4NEWd5qv2ilCAdl6qp26j3AobueHbvsw&s=AWVe9Ky82H5F9qu478ou4LiSS7_KaeqqTISXsQhowz4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH5VLU23ZE4JC4CQU4YQZMDPYVDKTANCNFSM4HQMGAYA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=AAyMc3HyvNY4xrJwcNGRFDnCT97iBHn6GqTfzmbL-gM&m=GvkpohlKeNF4NEWd5qv2ilCAdl6qp26j3AobueHbvsw&s=0iYTnniTRYQptPDb7DmUgIXKjk5oSW4iqgqPkkN_m1Q&e=>
> .
>


-- 

Shachar Chen
24/7 Operation Lead
T: +972-74-700-4480
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
