### ISSUE TITLE
Add Screenshot to agent-file-sharing-overview.md

### ISSUE THREAD

**Issue by jamushill** [LivePersonInc/knowledge-center-archive#53]
Hey LivePeople,

I tried to open a suggestion, but it was trying to make me fork the repository which seems wrong.

My suggestion is that agent-file-sharing-overview.md should have a screenshot of what it looks like for a customer to receive a non-image file.  It shows what that looks like to the agent, but not to the visitor.

Cheers,

**Comment by EdenKupe** [comment]
Hey, you're in the right place :)

@lonz87 can you please take a look at creating the screenshot :)

**Comment by EdenKupe** [comment]
@cdougherty328 need help here?

**Comment by cdougherty328** [comment]
Thanks for your feedback! This image has now been added to the file sharing overview.
