### ISSUE TITLE
Structured content list documentation for inApp + Web Messaging

### ISSUE THREAD

**Issue by rvidal-lp** [LivePersonInc/knowledge-center-archive#54]
RBS are asking for examples from the consumer experience side of this feature for InApp and Web.

**Comment by EdenKupe** [comment]
@lonz87 can we accommodate this request please?

**Comment by lonz87** [comment]
I have reached out to agent workspace team

**Comment by rvidal-lp** [comment]
We’re interested in the consumer experience, not the agent experience please.

Thank you.

**Comment by lonz87** [comment]
No worries, I am on it.

**Comment by lonz87** [comment]
Hi @rvidal-lp . I am going to add some of these GIFs from the following: https://docs.google.com/presentation/d/120bQjCb5v_8PMd2sHhXW8YhsS3TWAWMa6_KIaqKl1E8/edit#slide=id.g3bf00a3d1d_0_25

Will update you when images are live - waiting for them to be resized. 

Thanks!

**Comment by rvidal-lp** [comment]
Do you have an ETA please? Thanks.

**Comment by lonz87** [comment]
hi @rvidal-lp 

I went to add several images from the consumer side to this article: https://knowledge.liveperson.com/messaging-channels-rich-messaging-structured-content-for-messaging-user-guide.html 

BUT - I see it already has 3 images depicting structured content from consumer side. Did you mean you wanted specifically structured content as it looks in web messaging and in-app from the consumer side? Or, are you looking for a specific list? Is that the article you were referring to?

Please calrify and see this doc to flag any images that fit your needs: https://docs.google.com/presentation/d/120bQjCb5v_8PMd2sHhXW8YhsS3TWAWMa6_KIaqKl1E8/edit#slide=id.g3ad761d798_0_406

Thanks,

Elana

**Comment by rvidal-lp** [comment]
Hi Elana,

RBS have spotted that structured content list and time pickers are now available on SDK and Web messaging channels according to this page: https://developers.liveperson.com/getting-started-with-rich-messaging-rich-messaging-channel-capabilities.html
They want to see consumer-side examples before investing in development effort. Do we have any?

Thanks

**Comment by rvidal-lp** [comment]
Any updates please?

Thanks.

From: Remy Vidal <rvidal@liveperson.com>
Date: Tuesday, 11 June 2019 at 09:26
To: EdenKupe/knowledge-center <reply@reply.github.com>, EdenKupe/knowledge-center <knowledge-center@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [EdenKupe/knowledge-center] Structured content list documentation for inApp + Web Messaging (#54)

Hi Elana,

RBS have spotted that structured content list and time pickers are now available on SDK and Web messaging channels according to this page: https://developers.liveperson.com/getting-started-with-rich-messaging-rich-messaging-channel-capabilities.html
They want to see consumer-side examples before investing in development effort. Do we have any?

Thanks

**Comment by EdenKupe** [comment]
@lonz87 ?

**Comment by lonz87** [comment]
@rvidal-lp I have sent 2 emails to the PM requesting the images, the minute she gets them to me I will add. Will update you when that happens.

**Comment by lonz87** [comment]
![image](https://user-images.githubusercontent.com/44767185/59561004-21647e80-9023-11e9-984b-10dd6ba117ab.png)

This has been uploaded to the article.

**Comment by lonz87** [comment]
@rvidal-lp let me know if this is sufficient. I also have 
![image](https://user-images.githubusercontent.com/44767185/59561024-5b358500-9023-11e9-8776-61145c2d20aa.png)

**Comment by lonz87** [comment]
See updated article here: https://knowledge.liveperson.com/messaging-channels-rich-messaging-structured-content-for-messaging-user-guide.html

Let me know if this has answered your needs @rvidal-lp and I will close this issue. thanks

**Comment by rvidal-lp** [comment]
Thanks – do we have examples of time picker on Web + inApp?

**Comment by lonz87** [comment]
I can get if you think this is very important to add, but I think the article has sufficient images for now, especially as I just added the original image you requested - structured content for lists on inapp from the consumer side. If there is an important reason you also need specifically timepickers, then let me know. If not, then let's leave it as it is so it won't get too crowded. Thanks for your input @rvidal-lp
