### ISSUE TITLE
Issues found with Knowledge Center and articles missing thus far

### ISSUE THREAD

**Issue by X-Centric5** [LivePersonInc/knowledge-center-archive#55]
https://knowledge.liveperson.com/messaging-channels-messaging-channels-capabilities-comparison.html -->> The word "Accessibility" is miswritten, first column, last row of "Consumer Experience and above "Rich messaging".

After searching, I was not able to find a specific article explaining skills, which are assigned to agents, and their importance for routing and engagements. I suggest creating an article for this. For any doubts or questions, please feel free to message me.

**Comment by lonz87** [comment]
@X-Centric5  Hi thanks for your feedback, the spelling mistake has been fixed. 

@cdougherty328 can you please address the second Q (see above): "After searching, I was not able to find a specific article explaining skills, which are assigned to agents, and their importance for routing and engagements. I suggest creating an article for this. For any doubts or questions, please feel free to message me."

**Comment by DavLipman** [comment]
Hi,
@X-Centric5
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_X-2DCentric5&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=m0JBYDYlhRD6wfi5Jmb6x_vs8it4se1YKaGgSBWdYyI&s=KeIEDNrjMzlBY3sibZG0nEqecRxM7DhSOIFL8KXbHZY&e=>
-
please see article called Connect visitors to agents by skills
<https://knowledge.liveperson.com/admin-settings-skills-groups-connect-visitors-to-agents-by-skills.html>
 Link:
https://knowledge.liveperson.com/admin-settings-skills-groups-connect-visitors-to-agents-by-skills.html
,
This article explains what skills are and how to assign them to users and
engagements.
I have also added a sentence on their importance.
Thanks
Davina

Davina Lipman
Product Writer
T: +972-74-700-4557
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>


On Mon, Jun 3, 2019 at 1:23 PM lonz87 <notifications@github.com> wrote:

> @X-Centric5
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_X-2DCentric5&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=m0JBYDYlhRD6wfi5Jmb6x_vs8it4se1YKaGgSBWdYyI&s=KeIEDNrjMzlBY3sibZG0nEqecRxM7DhSOIFL8KXbHZY&e=>
> Hi thanks for your feedback, the spelling mistake has been fixed.
>
> @cdougherty328
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cdougherty328&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=m0JBYDYlhRD6wfi5Jmb6x_vs8it4se1YKaGgSBWdYyI&s=BtKqqBYzzNDEvPyLDNwErMTNhgS4bHwSS6M-jizn5v0&e=>
> can you please address the second Q (see above): "After searching, I was
> not able to find a specific article explaining skills, which are assigned
> to agents, and their importance for routing and engagements. I suggest
> creating an article for this. For any doubts or questions, please feel free
> to message me."
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_55-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAJNQH7LEJOVT6RQ3ZIVEADDPYTWJNA5CNFSM4HR6OATKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWY7DPI-23issuecomment-2D498201021&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=m0JBYDYlhRD6wfi5Jmb6x_vs8it4se1YKaGgSBWdYyI&s=OBbSJMMMOSaOndc7AMqO-9uffq1ERQ8ygA6XWIZu3So&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJNQH7MGABGY254PVX47SF3PYTWJNANCNFSM4HR6OATA&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=FEjqWPzlizGeYBe0-xFc012cMmrj7x6k-o7XnUJK8pQ&m=m0JBYDYlhRD6wfi5Jmb6x_vs8it4se1YKaGgSBWdYyI&s=Pw-pqd9MBBtmxHXVBwhvrRlE1piON1_gTuRvSfjDr7Q&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
Hey @X-Centric5 ,

Can we close this issue? Do you feel things have been covered?

Thanks!

**Comment by X-Centric5** [comment]
We may! Closing it now, thank you @EdenKupe  and @DavLipman !
