### ISSUE TITLE
Hyperlinking

### ISSUE THREAD

**Issue by X-Centric5** [LivePersonInc/knowledge-center-archive#59]
https://knowledge.liveperson.com/agent-manager-workspace-workspace-configuration-predefined-content-best-practices.html

After looking in the Predefined Content sections, I was not able to find a guide on how to hyperlink in them, which is the HTML hyperlink method. This can also be done in the engagement windows headers, I suggest a small guide is added as to how to hyperlink for both the PDC and engagement windows.

**Comment by EdenKupe** [comment]
I added a note about PDC accepting HTML syntax, I believe it's sufficient.

can you point me to where you'd add the note about engagement window headers?

**Comment by X-Centric5** [comment]
Thank you for your swift response Eden! I would add a note here: https://knowledge.liveperson.com/contact-center-management-campaigns-engagement-window.html

Something of the sort of: "Hyperlinking can be done here as well, in the same way as on the Predefined content" (this part linking to the original HTML method).

**Comment by EdenKupe** [comment]
Hey! I'm not sure which part of the engagement window can be turned into a link. The window name? When you say header, what exactly do you mean?

**Comment by EdenKupe** [comment]
@X-Centric5 hey, did you catch my question above?

**Comment by X-Centric5** [comment]
Yes, sorry for the long time to respond. It is the header. It's fine, we can close this issue now. :)
