### ISSUE TITLE
Article regarding SSO is missing

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#60]
I noticed that I'm unable to access this article today, receiving 404 error.
https://knowledge.liveperson.com/security-regulations-sso-unified-login.html

Please put it back as soon as possible, thank you.

Regards,
Yuri Korogi

**Comment by EdenKupe** [comment]
A redirect is now in place and will send you to the right address for this article.

**Comment by ykorogi** [comment]
@EdenKupe 

Hi Eden,

I checked it on multiple browsers today, but still receiving 404 Error.

These are the links we've sent to customer.
https://knowledge.liveperson.com/security-regulations-sso-unified-login.html
https://knowledge.liveperson.com/security-regulations-sso-unified-login.html#configuration-on-the-customers-environment

Also, at the top page https://knowledge.liveperson.com/, if you type SSO and click the first article that appears, which is above article, you also get 404 error. 

Would you please check again?

Regards,
Yuri
