### ISSUE TITLE
Change url

### ISSUE THREAD

**Issue by ranmeirovich** [LivePersonInc/knowledge-center-archive#61]
https://knowledge.liveperson.com/getting-started-getting-started-with-live-chat.html

Change:
To get started, access LivePerson using this link: https://va-a.authentication.liveperson.net/login.html

To:
To get started, access LivePerson using this link: https://authentication.liveperson.net/

**Comment by EdenKupe** [comment]
@lonz87 can you fix this?

**Comment by lonz87** [comment]
The link has been updated 👍 @ranmeirovich thanks for the update!

**Comment by ranmeirovich** [comment]
👍😁💰

On Sun, Jun 23, 2019 at 10:00 AM lonz87 <notifications@github.com> wrote:

> Closed #61
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_61&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=u3PeMmRREzJefPbrTDVtUFfR_KyxulAGjlyZjDbKFns&m=JgI2oZGf73lsMbqanpN7GoILqxUMp1pMotPhss6Tv3M&s=9BR5Z1h2uPTdMKUCypClKvojCnipF6pVwRqpMFYI7tw&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_61-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAMNAJJ45WPT2ML643AHE6DLP34NPPA5CNFSM4HZSDD42YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSD45PII-23event-2D2432292769&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=u3PeMmRREzJefPbrTDVtUFfR_KyxulAGjlyZjDbKFns&m=JgI2oZGf73lsMbqanpN7GoILqxUMp1pMotPhss6Tv3M&s=F_yoatXrrLfGnCloa_UsS2TtOojlqUA9sd1-WH8EEPw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMNAJJY6P3BOGVQKF4XWSIDP34NPPANCNFSM4HZSDD4Q&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=u3PeMmRREzJefPbrTDVtUFfR_KyxulAGjlyZjDbKFns&m=JgI2oZGf73lsMbqanpN7GoILqxUMp1pMotPhss6Tv3M&s=oQl3k9_W9ScRkwk3dT6NhYRHIgSw_o0sCW_pm6fqJPU&e=>
> .
>


-- 

Ran Meirovich
Support Operations Leader
T: +972-74-700-4457
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands. <https://bit.ly/2RS120I>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
