### ISSUE TITLE
Contradictory information about font inheritance of chat window elements

### ISSUE THREAD

**Issue by DKatsov** [LivePersonInc/knowledge-center-archive#65]
In this article https://knowledge.liveperson.com/contact-center-management-campaigns-engagement-window.html, the statement "Text is the same ............. font as the Automatic Messages" about the font regarding chat window elements contradicts the fact that in the Engagement Window Studio the fonts of the elements can be customized individually. The text about the font needs to be deleted or clarified.

**Comment by lonz87** [comment]
@cdougherty328

**Comment by cdougherty328** [comment]
This has been corrected
