### ISSUE TITLE
Broken link for Google Dialogue Flow connection

### ISSUE THREAD

**Issue by kohcheek** [LivePersonInc/knowledge-center-archive#67]
A 404 Not Found error showed up when user click on Google dialogue flow link under Step 2B "Connection" section.
https://knowledge.liveperson.com/getting-started-getting-started-with-bots.html#step-2-implement-automation-and-build-a-bot
![DialogFlowLink-404NotFound](https://user-images.githubusercontent.com/29918042/60478264-a4890400-9cb4-11e9-8f11-d6fb9d6816f1.png)

**Comment by EdenKupe** [comment]
@lonz87 are you on this?

**Comment by lonz87** [comment]
@kohcheek replaced link, thanks for pointing out.
