### ISSUE TITLE
Update documentation to reflect deprecation of domain name botcentralai.com

### ISSUE THREAD

**Issue by kohcheek** [LivePersonInc/knowledge-center-archive#68]
Since botcentralai.com will be deprecated and we're pointing to developers/users to our sites to get tutorial on how to use Conversation Builder, will need to replace with updated domain name.
eg.
From:
https://knowledge.liveperson.com/ai-bots-automation-conversation-builder-conversation-builder-overview.html
link to "tutorials and guides on the Conversation Builder" which goes to:
https://developers.liveperson.com/conversation-builder-getting-started-1-dialogs-and-patterns.html
there is "....navigate to https://platform.botcentralai.com, enter your credentials, select your region, and log in."

There are other places which mention botcentralai.com
eg
https://developers.liveperson.com/conversation-builder-getting-started-3-integrations.html
https://developers.liveperson.com/custom-third-party-bots.html

**Comment by EdenKupe** [comment]
Hey,

Can you please reopen this issue on the Developers' Community? [It's here](https://github.com/LivePersonInc/developers-community).
