### ISSUE TITLE
Facebook Messenger page missing direction

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#69]
https://knowledge.liveperson.com/messaging-channels-facebook-messenger.html

On above page, there's direction saying
"On the Facebook connector page, under Add a Facebook external user, **simply select the Facebook External User profile you have just created** and click Done."

However, there's no direction above this that is giving any direction on how to create Facebook external user.  Please add detail direction on how to create "Facebook External User profile" so that it will be clear.

**Comment by ykorogi** [comment]
I think the step that's missing in above article is written in this document.

*Facebook Messenger Connector Product Overview (see page 37 & 38) : https://docs.google.com/presentation/d/1Yn6tIcQt6DbzS7im51a_A4leMWH5UKgIMcp5vWHMWhU/edit#slide=id.g2578b6bc56_0_37

Customer needs visibility to this detail procedure so please add it to above Knowledge Center article

**Comment by cdougherty328** [comment]
This has been resolved. Thank you!
