### ISSUE TITLE
Messaging channels table

### ISSUE THREAD

**Issue by kstrickland09** [LivePersonInc/knowledge-center-archive#7]
The table on the Messaging channels capabilities page runs off the screen and there is no horizontal scroll to see the elements off the screen.  Consider using check mark (&#10003;) instead of the word "supported" to save some space. Table width is currently set to 135%, also.

https://knowledge.liveperson.com/messaging-channels-messaging-channels-capabilities-comparison.html

**Comment by EdenKupe** [comment]
Thanks for reporting. Which screen were you viewing the table on?

**Comment by kstrickland09** [comment]
It was an external monitor, about 28" screen with a 16:9 aspect ratio. On
my 15" laptop I don't see the issue unless I resize the window to be more
widescreen.


Thanks!

Kristin Strickland
Senior Solutions Engineer
T: +1 (770) 431-6348
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.


On Tue, Mar 26, 2019 at 4:16 AM Eden Kupermintz <notifications@github.com>
wrote:

> Thanks for reporting. Which screen were you viewing the table on?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_7-23issuecomment-2D476518717&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=mMG_FyRBsN_-gRDdORbTnMCq5osOqsdOPb6SDq-b0m4&m=8c9Frt4HC-zrq-1-T1ufVyZvVFQtojwBgjc73mjEOR4&s=o0hW8yGy7EMREn-pZrkkLgz3-3dIP2mLVN9ChBsT9Lg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APYM1X-2DemPhoBb8Bt0B-2D9yPzbqQmGG-5Fdks5vaddpgaJpZM4cIMm7&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=mMG_FyRBsN_-gRDdORbTnMCq5osOqsdOPb6SDq-b0m4&m=8c9Frt4HC-zrq-1-T1ufVyZvVFQtojwBgjc73mjEOR4&s=35zXW6Y9zZKjySEOMtK1GHVcErBAXG2WeiyrH5YcPkI&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by mjansonius** [comment]
For Whatsapp, at least the following are both supported by the channel and working with LiveEngage:

- Delivered indication - (message from) consumer to agent 
- Delivered indication - (message from) agent to consumer
- Read indication - (message from) agent to consumer

Only the Read indication for messages from consumer to agent is not working, i.e. no blue checkmarks in the Whatsapp interface for the customer

**Comment by EdenKupe** [comment]
@lonz87 can you confirm the latest comment on this issue?

**Comment by lonz87** [comment]
@mjansonius I have contacted the PM for confirmation - will keep you updated. Thanks for the feedback!

**Comment by EdenKupe** [comment]
@kstrickland09 I think I'm missing something here, I can't reproduce. Why would a bigger screen hide parts of the table?

can you send a screenshot?

**Comment by kstrickland09** [comment]
I was thinking the break point for the responsive design my be height
(which would be unusual, admittedly). In either case, I can't repro today.
Let's just assume my machine/browser was being cranky. Sorry for the false
alarm!


Kristin Strickland
Senior Solutions Engineer
T: +1 (770) 431-6348
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/LivePersonInc>
Our mission is to make life easier by transforming how people communicate
with brands.


On Thu, Mar 28, 2019 at 7:47 AM Eden Kupermintz <notifications@github.com>
wrote:

> @kstrickland09
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kstrickland09&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=mMG_FyRBsN_-gRDdORbTnMCq5osOqsdOPb6SDq-b0m4&m=PUNR6n_iExzVWZ9ojaMQcyQPaO3i5RvezCS5wjuuvKI&s=wjBAONHhHaUd6U6jYplG8SLKjw1hkGpSOq6IhtOA-eU&e=>
> I think I'm missing something here, I can't reproduce. Why would a bigger
> screen hide parts of the table?
>
> can you send a screenshot?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_7-23issuecomment-2D477562181&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=mMG_FyRBsN_-gRDdORbTnMCq5osOqsdOPb6SDq-b0m4&m=PUNR6n_iExzVWZ9ojaMQcyQPaO3i5RvezCS5wjuuvKI&s=d7dNStweWBTlQUC6ejnWS6XWz6dNpeNqDAtSwRAeqCE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APYM1c7h7dhOjjA7ov8JHzJsnIT2imADks5vbKvQgaJpZM4cIMm7&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=mMG_FyRBsN_-gRDdORbTnMCq5osOqsdOPb6SDq-b0m4&m=PUNR6n_iExzVWZ9ojaMQcyQPaO3i5RvezCS5wjuuvKI&s=rQXq9rFRuGs9WiMve3DwJyIaNZFCsKkranJmk0F4JbM&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.

**Comment by EdenKupe** [comment]
All good, this kind of tables (lot of info and cells) can be annoying so I'll keep any eye out :) Keeping this issue open until we update the fields requested above :)

**Comment by EdenKupe** [comment]
@lonz87 are we good here? Is the table updated?

**Comment by lonz87** [comment]
@mjansonius Thanks for pointing this out. 3 fields were updated accordingly. Just to clarify: On WhatsApp - Read indication - consumer to agent is supported, meaning the agent will be notified once message is read by consumer. The agent to consumer is not.
