### ISSUE TITLE
Update request on Facebook Messenger article

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#72]
On this page,
https://knowledge.liveperson.com/messaging-channels-facebook-messenger.html#adding-an-agent-manager-user-to-display-third-party-messages

after "On the Facebook connector page, under Add a Facebook external user, simply select the Facebook External User profile you have just created and click Done." 

Please add following statement (for better clarification of what user to select/not select).

-----------------
**NOTE:** Please make sure NOT to select actual agent user taking conversations here. Make sure to select Agent Manager user (Facebook external user) you just created dedicated just for this purpose.
-----------------

**Comment by ykorogi** [comment]
![Capture](https://user-images.githubusercontent.com/49143186/60655380-968bdc80-9e88-11e9-9cc7-f58b2a5d9506.PNG)

Where the comment is requested to be added. (highlighted in YELLOW)

**Comment by cdougherty328** [comment]
This disclaimer has been added to the Facebook overview, thanks!
