### ISSUE TITLE
Weird login page to report builder videos

### ISSUE THREAD

**Issue by EdenKupe** [LivePersonInc/knowledge-center-archive#74]
Hey guys,

When you click the link on [this page](https://knowledge.liveperson.com/data-reporting-report-builder-training-tutorials.html), you get to a weird login screen. [This is its address](https://liveperson.elasticlearning.online/).

Are we familiar with this page? Is this the intended behavior?

**Comment by EdenKupe** [comment]
@lonz87

**Comment by lonz87** [comment]
@DavLipman can you please check if this is intentional and the right address? If not, let's replace with working link or remove.

**Comment by DavLipman** [comment]
Hi,
The training tutorials are part of the LivePerson Institute documentation which offers in-depth training and certification courses for professionals who manage messaging programs using LiveEngage. To access these trainings, it is necessary to log in but the log in is extremely basic and simple and is just to monitor usage of the tutorials.
