### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by X-Centric5** [LivePersonInc/knowledge-center-archive#75]
Document: https://knowledge.liveperson.com/security-regulations-liveperson-disaster-recovery.html

Typo resides in "Failover decision and recovery window". "Once a decision is made, it can take up to 30 2 hours minutes for the disaster..." Should be 30 mins according to document: https://drive.google.com/file/d/1dIx8KGzf3bIEvL59UYFPDJ7C6wASF3fN/view

Thank you!

**Comment by cdougherty328** [comment]
Thank you for catching this, it has been corrected.
