### ISSUE TITLE
Vieport meta tag example missing

### ISSUE THREAD

**Issue by ykorogi** [LivePersonInc/knowledge-center-archive#77]
In this article:
https://knowledge.liveperson.com/messaging-channels-web-messaging-add-web-messaging-to-your-website.html#optimize-the-mobile-experience

On "Optimize the mobile experience" section, after "(Recommended) Add the viewport meta tag (as shown below) to the page code." the actual example of the meta tag is missing. Please add following examples.

**Our recommended viewport meta tag is as follows:**
`<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>`

**For the window to be embedded on mobile web, this is the minimal content required:** 
`<meta name="viewport" content="width=device-width">`

NOTE: Above meta tags are from this article. 
Web Messaging Configuration Guide (internal)
https://docs.google.com/document/d/1_C0NImvMhfkykflG5bOEWu-ic76mTauy8NS113qLz44/edit#heading=h.144ioedgm58a

**Comment by EdenKupe** [comment]
Thanks for the report. I've added this.
