### ISSUE TITLE
Auto close for messaging conversations

### ISSUE THREAD

**Issue by jeremywest1970** [LivePersonInc/knowledge-center-archive#79]
https://knowledge.liveperson.com/contact-center-management-messaging-operations-auto-close-for-messaging-conversations.html

Article below uses "Auto close timer" and "Inactivity Timer" interchangeably.  This is causing confusion with our clients as they are thinking this set the converstaion back to an active status, which is does not.  It just resets the autoclose timer.  We need to remove references to the Inactivity timer in this article.

Joining as “reader” resets the inactivity “timer”: The auto close "timer" is reset when an agent manager opens a conversation to view it in full screen or from the Open Connections list.
This is currently a technical limitation since the inactivity “timer” is reset with every metadata change of the conversation. An agent manager joining as a “reader” triggers a change in the conversation participant’s metadata.

**Comment by EdenKupe** [comment]
@cdougherty328 can we take a look at this and attempt to clear up the language?

**Comment by cdougherty328** [comment]
This language has been clarified, thanks!
