### ISSUE TITLE
Proactive notification examples is wrong and needs to be removed

### ISSUE THREAD

**Issue by ebramilp** [LivePersonInc/knowledge-center-archive#83]
Team,

Please remove this image: https://knowledge.liveperson.com/img/WhatsApp%20Proactive%20notifications%20Gif%20-2.gif
from this page:
https://knowledge.liveperson.com/messaging-channels-whatsapp-business.html

It is misleading because it shows a non authorized way to use the whatsapp product. Whatsapp policy does not allow sending proactive messages with promotional content in them (like the offer to purchase a product). This is creating false expectations for clients and causing a lot of friction.

Thanks
Eyal
ebrami@liveperson.com

**Comment by cdougherty328** [comment]
Hi Eyal, 

Thank you for your feedback on this. The WhatsApp Business overview has been updated to include two still screenshots of business activity alerts rather than this GIF that we had previously. Please let me know if there is anything else. 

Thanks!

**Comment by ebramilp** [comment]
Thanks!

Eyal Brami
WhatsApp Solution Lead
T: +1-770-431-6315
<https://www.linkedin.com/company/164748> <https://twitter.com/liveperson>
<https://www.facebook.com/liveperson/?ref=bookmarks>
Our mission is to make life easier by transforming how people communicate
with brands. <https://liveperson.docsend.com/view/drieh2u>


On Wed, Jul 31, 2019 at 4:15 AM cdougherty328 <notifications@github.com>
wrote:

> Hi Eyal,
>
> Thank you for your feedback on this. The WhatsApp Business overview has
> been updated to include two still screenshots of business activity alerts
> rather than this GIF that we had previously. Please let me know if there is
> anything else.
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EdenKupe_knowledge-2Dcenter_issues_83-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAKBTSZMJHTRTHM7QYTSURTLQCFQ4DA5CNFSM4IIAZAW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GZDCI-23issuecomment-2D516788617&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=YlVD0z6_ImyDhALMtNr4fM13fOyM6AXeaM54fnmwV0c&m=U75L837F6OandZrodKr-yOSgVb_mvkFh8fgLHB2f89k&s=GKX058jwx9PDS2FOIdQD3_FqxzE33iegJjCx70OAx38&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKBTSZJUFWHP5LJSGOOUC23QCFQ4DANCNFSM4IIAZAWQ&d=DwMCaQ&c=NxS7LVD4EucgUR9_G6bWzuqhmQ0xEJ2AZdqjz4WaSHU&r=YlVD0z6_ImyDhALMtNr4fM13fOyM6AXeaM54fnmwV0c&m=U75L837F6OandZrodKr-yOSgVb_mvkFh8fgLHB2f89k&s=v1wyjJy1Zsu-_I0ubegjqwTeKTl2ZpV0tH2cOMuWEIU&e=>
> .
>

-- 
This message may contain confidential and/or privileged information. 
If 
you are not the addressee or authorized to receive this on behalf of the 
addressee you must not use, copy, disclose or take action based on this 
message or any information herein. 
If you have received this message in 
error, please advise the sender immediately by reply email and delete this 
message. Thank you.
