### ISSUE TITLE
Clarification regarding ACD

### ISSUE THREAD

**Issue by Sergeyp52** [LivePersonInc/knowledge-center-archive#84]
Can you please add a line to dispel any ambiguity that our customers might have regarding ACD [here](https://knowledge.liveperson.com/contact-center-management-live-chat-operations-automatic-conversation-distribution.html#how-acd-works)?

Under "how ACD works", it says "If both agents have the same load ratio, the chat is routed to the agent with the longest idle time. Idle time is determined by the time elapsed since the agent received the last chat".

I propose to add that agent states do not affect their place in queue, so for example if I am the next one to accept a chat but I moved to Away status and back to Online, it will not "reset" my idle time and  I will not be overtaken by the next agent in the queue.

**Comment by lonz87** [comment]
Added that sentence for clarity. Thanks for your feedback @Sergeyp52 !

**Comment by lonz87** [comment]
@Sergeyp52 I see we added this exact note a couple of months ago. Is this line currently in the article insufficient in some way? If so , please let me know and I will correct:

Note: Agent states do not impact their place in queue, so, for example, if the agent next in queue to accept a chat moved to 'Away' status and then back to 'Online', the change of state will not reset the agent's idle time.

**Comment by EdenKupe** [comment]
@lonz87 @Sergeyp52 any updates here?

**Comment by lonz87** [comment]
As I mentioned, the above sentence was added months ago. @Sergeyp52 re-requested to add it in - I am wondering if there is something missing from the new sentence that was adding (see above). Currently, the article is updated with requested clarification.

**Comment by Sergeyp52** [comment]
@EdenKupe Hi, sorry about the delay in response. I found that one of the engineers who I worked with together on this opened the same request. Such efficiency and striving to improve!

Thanks :)
