### ISSUE TITLE
Additional information needs to be added to "configuring your firewall" to correct an inconsistency 

### ISSUE THREAD

**Issue by Hmalchev** [LivePersonInc/knowledge-center-archive#89]
Using the whitelist in the Admin Console for an account may lead to a IPpolicy issue for the post chat survey and controller bots, due to a missing IP in the range. The IP itself looks in range but it's not. This is the document:
https://knowledge.liveperson.com/security-regulations-security-configuring-your-firewall.html#ip-ranges-for-your-firewall-whitelist
These IP ranges need to be added to the whitelist for the bots:
172.16.0.0 - 172.31.255.255
10.16.0.0 - 10.31.255.255
10.32.0.0 - 10.47.255.255
10.48.0.0 - 10.63.255.255
10.160.0.0 - 10.175.255.255
10.176.0.0 - 10.191.255.255

**Comment by EdenKupe** [comment]
@DavLipman can we add these IPs please?

**Comment by DavLipman** [comment]
Added these IP ranges to the doc.
