### ISSUE TITLE
Casey Bot link not working

### ISSUE THREAD

**Issue by Fitch-LP** [LivePersonInc/knowledge-center-archive#92]
When you ask about AI it response with "LivePerson's AI engine, Maven has been making headlines! [Learn more here.](https://knowledge.liveperson.com/ai-bots-automation-maven-maven-overview.html)"

This link give a 404:
https://knowledge.liveperson.com/ai-bots-automation-maven-maven-overview.html

**Comment by EdenKupe** [comment]
Added a redirect, that link now works.
