### ISSUE TITLE
Whatsapp-onboarding: Broken link coming from LE

### ISSUE THREAD

**Issue by fgifford-liveperson** [LivePersonInc/knowledge-center-archive#96]
Within LiveEngage, when setting up a WhatsApp data source (https://[server].le.liveperson.net/a/[account id]/#/mng/data/sources/whatsapp/onboarding), there's a broken link to https://knowledge.liveperson.com/whatsapp-onboarding.html in the part of the page with this text:

> Create a branded WhatsApp Business profile and engage with your consumers through their favorite messaging app - WhatsApp.
> Learn more

- Assuming this link was once valid but was removed, please create a process to ensure you put in relevant redirects or error responses when removing content. 
- Please work with the LE people to implement some process to ensure that they are aware when content is removed.
- Please get LE to update this link, even if you've added a redirect.

Thanks.

**Comment by EdenKupe** [comment]
Hey,

This link was never valid, it was a part of a workaround the UI team used to move away from connection panel links. No content was removed.

I've added a redirect, which is what we've done with all of these links (where they were found, we did not have a full list). It now leads to the Whatsapp connector doc.
